# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: ai-backend
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - selenium

#   selenium:
#     image: selenium/standalone-chrome:4.32.0
#     platform: linux/amd64
#     container_name: selenium
#     ports:
#       - "4444:4444"
#     shm_size: 2gb

version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app           # Mount your code into the container
    working_dir: /app
    command: gunicorn -w 2 -b 0.0.0.0:8000 --timeout 120 main:app
    ports:
      - "8000:8000"
